# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_author',
            field=models.CharField(default=b'firstname_lastname', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='post_category',
            field=models.CharField(default=b'category', max_length=15),
        ),
    ]
