# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20160101_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_excerpt',
            field=models.CharField(default=b'Lorem ipsum dolor', max_length=400),
        ),
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(default=b'title', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(max_length=4000),
        ),
    ]
