# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160102_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_contributorname', models.CharField(default=b'firstname_lastname', max_length=30)),
                ('contributor_position', models.CharField(default=b'QLA Staff', max_length=20)),
                ('contributor_area', models.CharField(default=b'area', max_length=10)),
            ],
        ),
    ]
