# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_contributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='contributor_area',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='contributor_position',
        ),
        migrations.AddField(
            model_name='contributor',
            name='contributor_area1',
            field=models.CharField(default=b'area1', max_length=20),
        ),
        migrations.AddField(
            model_name='contributor',
            name='contributor_area2',
            field=models.CharField(default=b'area2', max_length=20),
        ),
        migrations.AddField(
            model_name='contributor',
            name='contributor_area3',
            field=models.CharField(default=b'area3', max_length=20),
        ),
        migrations.AddField(
            model_name='contributor',
            name='contributor_position1',
            field=models.CharField(default=b'QLA Staff', max_length=20),
        ),
        migrations.AddField(
            model_name='contributor',
            name='contributor_position2',
            field=models.CharField(default=b'QLA Staff', max_length=20),
        ),
        migrations.AddField(
            model_name='contributor',
            name='contributor_position3',
            field=models.CharField(default=b'QLA Staff', max_length=20),
        ),
    ]
