# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_contributor_contributor_biotext'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaIcons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialmediaicon_name', models.CharField(default=b'platform', max_length=30)),
                ('socialmediaicon_normal', models.CharField(default=b'link', max_length=30)),
                ('socialmediaicon_hover', models.CharField(default=b'hover_link', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='contributor',
            name='contributor_biotext',
            field=models.TextField(default=b'bio', max_length=3000),
        ),
    ]
