# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20160103_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaicon',
            name='socialmediaicon_link',
            field=models.CharField(default=b'hover_link', max_length=30),
        ),
        migrations.AlterField(
            model_name='socialmediaicon',
            name='socialmediaicon_hover',
            field=models.CharField(default=b'hover_img', max_length=30),
        ),
        migrations.AlterField(
            model_name='socialmediaicon',
            name='socialmediaicon_normal',
            field=models.CharField(default=b'img', max_length=30),
        ),
    ]
