# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20160103_0436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='contributor_contributorname',
            new_name='contributor_name',
        ),
    ]
