# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20160104_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='contributor_position2',
            field=models.CharField(blank=True, default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='contributor_position3',
            field=models.CharField(blank=True, default=b'', max_length=20),
        ),
    ]
