# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20160104_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='contributor_area1',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='contributor_area2',
            field=models.CharField(blank=True, default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='contributor_area3',
            field=models.CharField(blank=True, default=b'', max_length=20),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='contributor_name',
            field=models.CharField(default=b'Firstname Lastname', max_length=30),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='contributor_position1',
            field=models.CharField(default=b'', max_length=20),
        ),
    ]
