# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20160105_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='QLA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qla_author', models.CharField(default=b'firstname_lastname', max_length=30)),
                ('qla_title', models.CharField(default=b'title', max_length=100)),
                ('qla_excerpt', models.CharField(default=b'Lorem ipsum dolor', max_length=400)),
                ('qla_content', models.TextField(max_length=4000)),
                ('qla_thumb', models.CharField(default=b'fpo_square.PNG', max_length=30)),
                ('qla_date', models.DateTimeField(verbose_name=b'date published')),
            ],
        ),
    ]
