# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_qla'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyVignette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wv_author', models.CharField(default=b'firstname_lastname', max_length=30)),
                ('wv_title', models.CharField(default=b'title', max_length=100)),
                ('wv_excerpt', models.CharField(default=b'Lorem ipsum dolor', max_length=400)),
                ('wv_content', models.TextField(max_length=4000)),
                ('wv_cover', models.CharField(default=b'fpo_4x3.PNG', max_length=30)),
                ('wv_date', models.DateTimeField(verbose_name=b'date published')),
            ],
        ),
    ]
