# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20160108_2340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeeklyVignette',
            new_name='Blah',
        ),
    ]
